# Server
spring.application.name=backend
server.port=8081

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aeme_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_db}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password_db}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# OAuth2 Resource Server (Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:https://unrefrained-primal-harlee.ngrok-free.dev/realms/aeme}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:https://unrefrained-primal-harlee.ngrok-free.dev/realms/aeme/protocol/openid-connect/certs}

# Keycloak Admin
keycloak.server-url=${KEYCLOAK_SERVER_URL:https://unrefrained-primal-harlee.ngrok-free.dev}
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:aeme}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:aeme-client}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:BDZgYGfYfOnclVSAUPSIfoA1t0kyA7Ja}

# Sentry
sentry.dsn=${SENTRY_DSN:https://54ab0495e38221ea99a6e4bf15d88cf9@o4510801178460160.ingest.us.sentry.io/4511202969583616}
sentry.send-default-pii=true
sentry.traces-sample-rate=1.0
sentry.environment=${SPRING_PROFILES_ACTIVE:development}

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# Files
app.upload.dir=${UPLOAD_DIR:uploads}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-http-form-post-size=20MB
server.http2.enabled=false