# Server
spring.application.name=backend
server.port=8081

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/aeme_db
spring.datasource.username=user_db
spring.datasource.password=password_db
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# OAuth2 Resource Server (Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://unrefrained-primal-harlee.ngrok-free.dev/realms/aeme
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://unrefrained-primal-harlee.ngrok-free.dev/realms/aeme/protocol/openid-connect/certs

# Keycloak Admin
keycloak.server-url=http://localhost:8080
keycloak.admin.realm=aeme
keycloak.admin.client-id=aeme-client
keycloak.admin.client-secret=i7pZ6Vcz8QtKxL2Z2llI3Qe3rHGwdx3k

# CORS
cors.allowed-origins=http://localhost:5173

# Files
app.upload.dir=uploads